import type { Metadata } from "next";
import { ReactNode } from "react"
import "./globals.css";
import { MSWProvider } from "./_component/MSWComponent";

if (process.env.NEXT_RUNTIME === 'nodejs' && process.env.NODE_ENV !== 'production') {
  const {server} = require('@/mocks/http')
  server.listen();
}
type Props = { children: ReactNode };

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Props) {
  return (
    <html lang="en">
      <body>
        <MSWProvider>
          {children}
        </MSWProvider>
      </body>
    </html>
  );
}
