import type { Metadata } from "next";
import { ReactNode } from "react"
import "./globals.css";
import styles from './page.module.css';

type Props = { children: ReactNode, modal: ReactNode };

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: Props) {
  return (
    <html lang="en">
      <body>
        <div className={styles.container}>
          {children}
          {modal}
        </div>
      </body>
    </html>
  );
}
